# Generated by Django 4.2.16 on 2024-10-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=13, unique=True)),
                ('participant_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
